# Generated by Django 3.2.4 on 2021-08-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=200)),
                ('bar_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nutriscore', models.CharField(max_length=2)),
                ('proteins_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('energy_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fat_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fiber_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('carbohydrates_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('salt_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('saturated_fat_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sugars_100g', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.TextField()),
                ('url', models.TextField()),
                ('categories', models.ManyToManyField(to='search.Category')),
            ],
        ),
    ]
